### PR TITLE
Fix attribute error

### PR DESCRIPTION
**Pull request by emilyzhong**
* From new `disableScrollZoom` prop in #16

### CODE REVIEW

**Comment by mnogueron** [comment]
@emilyzhong I have been to quick to merge on this one. Will check it and merge, but it should all be good now!

**Comment by n1ru4l** [comment]
This could have been caught by a simple CI flow type check. Are you interested in adding a CI build? Could help this library being used by more people out there.

**Comment by mnogueron** [comment]
I don't think in that case Flow would have helped. We don't know what is expected inside `restPassThroughProps` as you are just passing down the props to the inner div. This error is a runtime error and would only have been spotted using a unit test for it.

For now I want to keep the CI as simple as it is, Flow type checking, unit tests and that's all. I might consider a more advanced CI pipeline in the future.

**Comment by n1ru4l** [comment]
Alright, I expected flow to actually catch setting unexpected types on the div element.

**Comment by n1ru4l** [comment]
We could create a test that renders the component and checks whether any warning has been logged to the console.

**Comment by mnogueron** [comment]
@n1ru4l It would not be that easy because someone might use specific attributes that are not regular HTML attributes. You would not be able to specify all possible attributes for a `div`.

But we should definitely think of a better way to removed unsupported props that we use in `PanZoom` but don't pass down. Using hooks would be a solution as you only need to deconstruct your props once, but it would force our users to have a React version compatible with hooks (>= 16.8.0).

I will investigate the value of having CI build and CD in the near future.

**Comment by mnogueron** [comment]
@n1ru4l 

> We could create a test that renders the component and checks whether any warning has been logged to the console.

Yes that's what I was thinking, you can help on that one if you feel like it, otherwise I will take care of it. But for now I need to go to work 😄

**Pull request merged**
