### PR TITLE
docs(readme): add documentation for methods getDragContainer and getContainer

### PR DESCRIPTION
**Pull request by n1ru4l**
These methods might be useful for some people. By adding them to the readme I want to ensure that their behaviour does not change without a major version bump.

### CODE REVIEW

**Comment by mnogueron** [comment]
@n1ru4l Thank you for your contribution!
Actually I don't think we should incorporate these functions in the documentation. For me they are part of the underlying implementation and should not be used outside of the component's own implementation.
I don't really see a good reason to directly get access to the div making this component, but maybe you have an example that I could review.

**Comment by n1ru4l** [comment]
@mnogueron
Here is an example: https://github.com/ombr/referentiel#usage
Here is my specific use-case: https://github.com/apclary/dungeon-revealer/blob/7280898372a79cb7828efe8b98e1169446970726/src/player-area.js#L246-L265

The library Referentiel requires you to pass a DOMElement to the constructor in order to calculate the event coordinates relative to the drag container element.

**Comment by mnogueron** [comment]
Would it be possible to pass the ref to the component you are rendering inside PanZoom instead of passing the PanZoom inner reference?
Something like:
```jsx
<PanZoom>
    <MyComponent ref={ref} />
</PanZoom>
```

**Comment by n1ru4l** [comment]
Yes, that would actually be possible:

```js
const MyComponent = React.forwardRef((props, ref) => (
  <div ref={ref}>asdasd</div>
));
const Foo = () => {
  const ref = useRef(null);
  return (
    <PanZoom
      onStateChange={() => {
        if (!ref.current) {
          return;
        }
        // do sth with ref.current.parentNode
      }}
    >
      <MyComponent ref={ref} />
    </PanZoom>
  );
};
```

However, that would also assume that the user knows the parent element of the PanZoom children has the transform applied 🤔

**Comment by mnogueron** [comment]
I think it should be fine. I don't think it is a common use case but it can still be supported by using refs inside your component. 

To me, users doing the same as you are quite adventurous and know a bit more about the library than common users 😄

I feel it safe to dismiss this question, if ref is covering your problem, even though it might be a bit more tricky to use. What do you think @n1ru4l

**Comment by n1ru4l** [comment]
I am fine with this solution for now 😊

When I got some spare time I will try migrating the internals to hooks which would allow us to provide both the primitives (hooks) and the current Component (which uses the hooks internally).

For advanced use-cases, users could then use the hooks instead of the Component.

**Comment by mnogueron** [comment]
@n1ru4l I think it's definitely a good direction!

**Pull request closed without merging**
